### ISSUE TITLE
Backspace to fix typos.

### ISSUE THREAD

**Issue by larsbrinkhoff** [MattisLind/papertapetext#1]
Being a sloppy typist, I made some typos making my paper tape.  Maybe future visitors might have the same experience.

I suggest adding support for typing backspace or delete to erase characters.  Untested:

```
    if (c == 0x08 || c == 0x7f) {
        if (i > 0) {
            i--;
            putchar(0x08); putchar(0x20); putchar(0x08);
        }
        continue;
    }
```

**Comment by MattisLind** [comment]
Thanks Lars!

That is a good idea to include a minimal line editor. The VT52 keyboard has seen some use so mistyping is common. I will include your patch.

**Comment by larsbrinkhoff** [comment]
Thanks!

I fixed an error: 0xff should be 0x7f for "delete".
